version: "3"
services:
  frontend:
    stdin_open: true
    build: ./chatbot_frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_API_DOMAIN=http://localhost:8080
    volumes: 
      - ./chatbot_frontend:/app
    depends_on:
      - backend
  backend:
    build: ./chatbot_backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=chatbot_backend
      - ADMIN_NAME=Huyen
      - ADMIN_EMAIL=phihuyen97.admin@gmail.com
      - ADMIN_PASSWORD=123456
      - JWT_SECRET_KEY=YiKi9EJgIYV7lS7iUskLZmt7xU9k0gAz
      - JWT_EXPIRES_TIME=86400000
      - PEPPER=wegkocgxjywglqrqzuefkxofxqtdkaqz
    volumes: 
      - ./chatbot_backend:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
